### ISSUE TITLE
Refactor `get_access_token()` for Cross Framework Compatibility.

### ISSUE THREAD

**Issue by s1dharth-s** [materials-marketplace/shieldapi#10]
### Issue Description

Currently, the [`get_access_token()`](https://github.com/materials-marketplace/shieldapi/blob/aad81530680ab9e826d40648a0c35cf351208b4f/shieldapi/frameworks/flask.py#L14C5-L14C21) function is located within shieldapi/frameworks/flask.py, making it specific to Flask. To enhance the reusability of this function across different frameworks, particularly Flask and FastAPI, it is proposed to move this function to a more centralized location, shieldapi/keycloak_utils.py. This change aims to promote code reusability and maintainability.  

### Expected Behavior

The get_access_token() function should be accessible and functional from both Flask and FastAPI contexts. After refactoring, the function should be able to extract the access token from the Authorization header of the request in both Flask and FastAPI.

**Comment by yoavnash** [comment]
The same is true for other functions such as [`get_userinfo`](https://github.com/materials-marketplace/shieldapi/blob/aad81530680ab9e826d40648a0c35cf351208b4f/shieldapi/frameworks/flask.py#L28).

**Comment by yoavnash** [comment]
There is a dependency on the Flask and therefore I will leave it as it is:
https://github.com/materials-marketplace/shieldapi/blob/aad81530680ab9e826d40648a0c35cf351208b4f/shieldapi/frameworks/flask.py#L22C19-L22C26
